services:
  fastapi-app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - fastapi_code:/app   # ephemeral volume
    ports:
      - "9000:8000"

  jupyter:
    image: jupyter/base-notebook
    volumes:
      - fastapi_code:/app   # same ephemeral volume
    ports:
      - "8889:8888"
    stdin_open: true
    tty: true
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --allow-root
      --no-browser

volumes:
  fastapi_code:
