name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-asyncio
          pip install jupyterlab ipykernel httpx pytest-asyncio

      - name: Run tests
        run: |
          cd fastapi-app
          export PYTHONPATH=$PYTHONPATH:$PWD
          pytest -q

      - name: Run notebooks
        run: |
          pip install nbconvert
          jupyter nbconvert --to notebook --execute notebooks/test_notebook.ipynb --output executed_test_notebook.ipynb